const WORD = 0; DEFINITION = 1;
SMALLWORDBANK =
[
	"extremity;The outermost or farthest point or portion.",
	"vendetta;A condition of private war in which the nearest of kin execute vengeance on the slayer of a relative; a blood-feud.",
	"concrete;Of or relating to an actual, specific thing or instance.",
	"professional;Conforming to the standards of a profession.",
];

TESTWORDBANK =
[
	"extremity;The outermost or farthest point or portion.",
	"vendetta;A condition of private war in which the nearest of kin execute vengeance on the slayer of a relative; a blood-feud.",
	"concrete;Of or relating to an actual, specific thing or instance.",
	"professional;Conforming to the standards of a profession.",
	"invention;A new device, method, or process developed from study and experimentation.",
	"convention;A formal meeting of members, representatives, or delegates, as of a political party, fraternal society, profession, or industry.",
	"maverick;A person who shows independence of thought and action, especially by refusing to adhere to the policies of a group to which he or she belongs.",
	"conscientious;Thorough and assiduous.",
	"carpophagous;Fruit eating.",
	"affinity;A spontaneous or natural liking or sympathy for someone or something.",
	"abnegation;Self-denial.",
	"erudite;Having or showing great knowledge or learning.",
	"candor;Frankness or sincerity of expression.",
	"aperture;An opening, such as a hole, gap, or slit.",
	"notorious;Known widely and usually unfavorably.",
	"negligible;Not significant or important enough to be worth considering.",
	"trifling;Of little worth or importance."
];

WORDBANK =
[
	"extremity;The outermost or farthest point or portion.",
	"vendetta;A condition of private war in which the nearest of kin execute vengeance on the slayer of a relative, a blood-feud.",
	"concrete;Of or relating to an actual, specific thing or instance.",
	"professional;Conforming to the standards of a profession.",
	"invention;A new device, method, or process developed from study and experimentation.",
	"convention;A formal meeting of members, representatives, or delegates, as of a political party, fraternal society, profession, or industry.",
	"maverick;A person who shows independence of thought and action, especially by refusing to adhere to the policies of a group to which he or she belongs.",
	"conscientious;Thorough and assiduous.",
	"carpophagous;Fruit eating.",
	"affinity;A spontaneous or natural liking or sympathy for someone or something.",
	"abnegation;Self-denial.",
	"erudite;Having or showing great knowledge or learning.",
	"candor;Frankness or sincerity of expression.",
	"aperture;An opening, such as a hole, gap, or slit.",
	"notorious;Known widely and usually unfavorably.",
	"negligible;Not significant or important enough to be worth considering.",
	"trifling;Of little worth or importance.",
	"prophylactic;Acting to defend against or prevent something, especially disease.",
	"reverie;An act or state of absent-minded daydreaming.",
	"pussyfoot;To act or proceed cautiously or timidly to avoid committing oneself.",
	"holistic;Emphasizing the importance of the whole and the interdependence of its parts.",
	"duly;In a proper manner.",
	"proselytize;To convert (a person) from one belief, doctrine, cause, or faith to another.",
	"collegiate;Of, relating to, or held to resemble a college.",
	"uncouth;Awkward or clumsy.",
	"cesspool;A filthy, disgusting, or morally corrupt place.",
	"impunity;Exemption from punishment, penalty, or harm.",
	"meta;Making or showing awareness of reference to oneself or to the activity that is taking place, especially in an ironic or comic way.",
	"whimsical;Playful or fanciful, especially in a humorous way.",
	"taxonomy;The classification and naming of organisms in an ordered system that is intended to indicate natural relationships, especially evolutionary relationships.",
	"mogul;Any great personage.",
	"equivocate;To use equivocal language to deceive someone or avoid committing oneself to a position.",
	"moniker;A personal name or nickname.",
	"clandestine;Kept or done in secret, often to conceal an illicit or improper purpose.",
	"scintillating;Animated, brilliant, or highly skilled.",
	"vicarious;	Experienced or felt by empathy with or imaginary participation in the life of another person.",
	"apatetic;Relating to or characterized by coloration serving as natural camouflage.",
	"fidelity;Faithfulness to obligations, duties, or observances.",
	"assart;To grub up trees and bushes to make land arable.",
	"odius;Deserving or causing hatred.",
	"vapid;Lacking taste, zest, or flavor.",
	"plasticity;Capability of being molded, formed, or modeled.",
	"ensemble;A group of people or things that make up a complete unit.",
	"acumen;Quickness, accuracy, and keenness of judgment or insight.",
	"guerilla;A person who engages in irregular warfare especially as a member of an independent unit carrying out harassment and sabotage.",
	"litigate;To prosecute or defend (a lawsuit or legal action).",
	"apathetic;Feeling or showing a lack of interest or concern.",
	"esoteric;Relating to or being a small group with specialized knowledge or interests.",
	"bigot;One who is strongly partial to one's own group, religion, race, or politics and is intolerant of those who differ.",
	"vernacular;The everyday language spoken by a people as distinguished from the literary language.",
	"voir dire;The formal examination of a prospective juror under oath to determine suitability for jury service or of a prospective witness under oath to determine competence to give testimony.",
	"sequestered;Remote or difficult to get to; isolated.",
	"galvanize;To arouse to awareness or action.",
	"heuristic;Of or relating to a usually speculative formulation serving as a guide in the investigation or solution of a problem.",
	"specious;Deceptively appealing.",
	"epithet;A term used to characterize a person or thing.",
	"peccadillo;A small sin or fault.",
	"paramount;Of chief concern or importance.",
	"palpable;Capable of being handled, touched, or felt.",
	"manna;Something of value that a person receives unexpectedly.",
	"pro forma;Done as a formality.",
	"affidavit;A written declaration made under oath before a notary public or other authorized officer.",
	"referendum;The principle or practice of submitting to popular vote a measure passed on or proposed by a legislative body or by popular initiative.",
	"tarry;Delay.",
	"crescendo;A steady increase in intensity or force.",
	"immutable;Not subject or susceptible to change.",
	"hunky-dory;Being satisfactory or in satisfactory condition.",
	"semblance;An outward or token appearance.",
	"monochromatic;Having or appearing to have only one color.",
	"srif;The short cross-line put as a finish at the ends of the terminating or unconnected strokes of roman or italic types.",
	"tenure;A fixed period of time during which a person holds a job or position.",
	"dogma;A doctrine or a corpus of doctrines relating to matters such as morality and faith, set forth in an authoritative manner by a religion.",
	"hygiene;Conditions and practices that serve to promote or preserve health.",
	"de facto;Existing in actuality, especially when contrary to or not established by law.",
	"gung ho;Extremely enthusiastic and dedicated.",
	"cutting edge;The position of greatest advancement or importance.",
	"progeny;A child or children of a parent or parents.",
	"acquiesce;To consent or comply passively or without protest.",
	"indelible;Impossible to remove, erase, or wash away.",
	"loquacious;Very talkative.",
	"poignant;Arousing deep emotion, especially pity or sorrow.",
	"don;To put on (clothing).",
	"aphrodisiac;Arousing or intensifying sexual desire.",
	"portly;Having a round, stout body.",
	"non sequitur;A statement that does not follow logically from what preceded it.",
	"behest;An authoritative command or urgent request.",
	"smorgasbord;A varied collection.",
	"breve;A symbol (˘) placed over a vowel to show that it has a short sound.",
	"fubar;Utterly botched or confused.",
	"promiscuous;Having casual sexual relations frequently with different partners.",
	"gynecology;The branch of medicine dealing with health care for women, especially the diagnosis and treatment of disorders affecting the female reproductive system.",
	"artifice;Something contrived or made up to achieve an end, especially by deceiving.",
	"gamely;In a willing and spirited fashion.",
	"gregarious;Seeking and enjoying the company of others.",
	"gaslight;Psychological manipulation of a person usually over an extended period of time that causes the victim to question the validity of their own thoughts, perception of reality, or memories.",
	"pensive;Engaged in deep and serious thought.",
	"rehash;To bring forth again in another form without significant alteration.",
	"lethargy;A lack of energy or vigor.",
	"appropriation;A legislative act authorizing the expenditure of a designated amount of public funds for a specific purpose.",
	"misconstrue;To mistake the meaning of.",
	"hubris;Overbearing pride or presumption.",
	"ignominious;Characterized by or deserving shame or disgrace.",
	"contentious;Fond of contention, quarrelsome.",
	"carrion;Dead and decaying flesh.",
	"anemic;Lacking force, vitality, or spirit.",
	"frump;A staid, drab, old-fashioned person.",
	"wanton;Exciting or expressing sexual desire.",
	"tenacious;Extremely persistent in adhering to or doing something.",
	"jaded;Made dull, apathetic, or cynical by experience or by having or seeing too much of something.",
	"prima donna;A vain or undisciplined person.",
	"carpe diem;Seize the day, used as an admonition to seize the pleasures of the moment without concern for the future.",
	"admonition;Cautionary advice or warning.",
	"subterfuge;Deception used to achieve an end.",
	"collateral;Property (such as securities) pledged by a borrower to protect the interests of the lender.",
	"dexterity;Skill and grace in physical movement, especially in the use of the hands.",
	"boudoir;A private sitting room, dressing room, or bedroom, especially one belonging to a woman.",
	"bravado;A show of bravery or defiance, often in order to make a false impression or mislead someone.",
	"chauvinism;Prejudiced belief in the superiority of one's own gender, group, or kind.",
	"innundate;To overwhelm as if with a flood; swamp.",
	"apprehensive;Anxious or fearful about the future.",
	"tawdry;Shameful or indecent.",
	"jager secret;The act of revealing information disseminated to a confidant during a period of intoxication.",
	"withholding;To refrain from giving or granting.",
	"bureaucracy;Administration of a government chiefly through bureaus or departments staffed with nonelected officials.",
	"moot;Of no practical importance; irrelevant.",
	"taxidermy;The art or operation of preparing, stuffing, and mounting the skins of dead animals for exhibition in a lifelike state.",
	"blasé;Unconcerned; nonchalant.",
	"callous;Emotionally hardened, unfeeling.",
	"arrivederci;Till we meet again, goodbye.",
	"pretentious;Showing or betraying an attitude of superiority.",
	"audit;An examination of records or financial accounts to check their accuracy.",
	"tacit;Not spoken.",
	"gigolo;A man who is hired as an escort.",
	"sabbatical;Relating or appropriate to the Sabbath as the day of rest.",
	"aplomb;Complete and confident composure or self-assurance,poise.",
	"ornery;Mean-spirited, disagreeable, and contrary in disposition.",
	"czar;A person having great power or authority.",
	"impotent;Incapable of sexual intercourse because of an inability to achieve or sustain an erection.",
	"pander;To cater to the lower tastes and desires of others or exploit their weaknesses.",
	"rictus;A gaping grimace.",
	"gauche;Lacking grace or social polish.",
	"caveat;A modifying or cautionary detail to be considered when evaluating, interpreting, or doing something.",
	"swarthy;Having a dark complexion or color.",
	"diatribe;A bitter, abusive denunciation.",
	"oblique;Not straightforward.",
	"reticent;Inclined to keep one's thoughts, feelings, and personal affairs to oneself.",
	"covetous;Very desirous, eager to obtain.",
	"bleak;Lacking in warmth, lige, or kindliness.",
	"ideogram;A picture that represents not the object pictured by a thing or idea that the object pictured is supposed to suggest.",
	"capacious;Capable of containing a large quantity.",
	"soppy;Showing or feeling too much of emotions such as love or sympathy.",
	"inure;To accustom to accept something undesirable, especially by prolonged subjection.",
	"penitents;Feeling or expressing remorse for one's misdeeds or sins.",
	"forays;A venture or an initial attempt, especially outside one's usual area.",
	"ardor;Intensity of emotion,especially strong desire, enthusiasm, or devotion.",
	"drubbing;A severe thrashing.",
	"unassuming;Exhibiting no pretensions, boastfulness, or ostentation.",
	"austere;Severe or stern in disposition or appearance.",
	"astringent;Sharp and penetrating.",
	"zany;Comical or ludicrous because of incongruity or strangeness.",
	"derelict;Neglectful of duty or obligation.",
	"diastema;A space or gap between two teeth.",
	"forcep;An instrument resembling a pair of pincers or tongs, used for grasping manipulating, or extracting.",
	"bijou;A small, exquisitely wrought trinket.",
	"doggedness;Grim resolution or persistence.",
	"chartreuse;Yellow-green.",
	"gyrate;To revolve around a fixed point or axis.",
	"delegate;To entrust to another.",
	"eddies;A current, as of water or air, moving contrary to the direction of the main current, especially in a circular motion.",
	"minutia;A small particular or detail.",
	"fatuous;Foolish or silly, especially in a smug or self-satisfied way.",
	"arcane;Known or understood by only a few.",
	"lithe;Readily bent, folded, or manipulated, supple.",
	"baroque;Extravagant, complex, or bizarre, especially in ornamentation.",
	"venerable;Commanding respect by virtue of age, dignity, character, or position.",
	"herald;One that gives a sign or indication of something to come.",
	"espouse;To adhere to or advocate.",
	"pedantic;Characterized by a narrow, often ostentatious concern for academic knowledge and formal rules.",
	"extrapolate;To infer or estimate by extending or projecting known information.",
	"liaison;An instance or a means of communication between different groups or units of an organization.",
	"hedge;A line of people or objects forming a barrier.",
	"auxiliary;Giving assistance or support.",
	"insolence;Overbearing or defiant behavior.",
	"gall;Outrageous insolence.",
	"lyrical;Expressing deep personal emotion or observations.",
	"diaspora;A group of people who live outside the area in which they had lived for a long time.",
	"hearth;The floor of a fireplace, usually extending into a room and paved with brick, flagstone, or cement.",
	"lexicon;A stock of terms used in a particular profession, subject, or style.",
	"emasculate;To deprive of strength or vigor.",
	"sober;Straightforward and serious.",
	"carcinogenic;Cancer causing.",
	"celibacy;Abstinence from sexual relations and/or marriage.",
	"exorbitant;Going beyond what is reasonable or customary, especially in cost or price.",
	"faux pas;A social blunder.",
	"ersatz;Being a usually inferior imitation or substitute.",
	"murk;Partial or total darkness.",
	"charlatan;One who pretends to knowledge, skill, importance, etc., which he does not possess.",
	"edification;A building, or intellectual, moral, or spiritual improvement.",
	"executrix;A female executor.",
	"repartee;A swift, witty reply.",
	"humblebrag;A seemingly modest, self-critical, or casual statement or reference that is meant to draw attention to one's admirable or impressive qualities or achievements.",
	"stochastic;Of, relating to, or characterized by conjecture.",
	"exegesis;Critical explanation or analysis, especially of a text.",
	"cognition;The mental process of knowing, including aspects such as awareness, perception, reasoning, and judgment.",
	"trow;To think or suppose.",
	"matriculate;To admit or be admitted into a group, especially a college or university.",
	"declamation;A speech marked by strong feeling.",
	"equivocate;To use equivocal language to deceive someone or avoid committing oneself to a position.",
	"ecumenical;Of worldwide scope or applicability, universal.",
	"autochthonous;Originating or formed in the place where found.",
	"chthonic;Pertaining to the earth.",
	"ad hoc;For the specific purpose, case, or situation at hand and for no other.",
	"infinitesimal;Immeasurably or incalculably minute.",
	"portmanteau;A word formed by merging the sounds and meanings of two different words.",
	"laconic;Using or marked by the use of few words.",
	"posterity;Future generations.",
	"beget;To cause to exist or occur.",
	"solipsism;The theory that the self is the only thing that can be known and verified.",
	"droll;Amusingly odd or whimsically comical.",
	"impertinent;Exceeding the limits of propriety or good manners.",
	"enumeration;The act or process of making or stating a list of things one after another, or the list itself.",
	"eisegesis;A subjective method of interpretation by introducing one's own opinions into the original.",
	"paradigm;One that serves as a pattern or model.",
	"dreck;Worthless, distasteful, or nonsensical material.",
	"attainder;Extinction of the civil rights and capacities of a person upon sentence of death or outlawry usually after a conviction of treason.",
	"vice;A practice or habit considered to be evil, degrading, or immoral.",
	"usurp;To take over or occupy without legal authority.",
	"recondite;Not easily understood.",
	"nick;A shallow notch, cut, or indentation on an edge or a surface.",
	"valor;Courage and boldness, as in battle.",
	"languid;Showing little or no vitality or animation.",
	"fanual;The animals characteristic of a region, period, or special environment.",
	"nepotism;Favoritism shown or patronage granted to relatives, as in business.",
	"filibuster;The obstructing or delaying of legislative action, especially by prolonged speechmaking.",
	"codify;To establish or express in a conventional form or standard formulation.",
	"convoluted;Complicated.",
	"admonish;To counsel against something to be avoided or warn.",
	"mar;To inflict damage, especially disfiguring damage, on, maim.",
	"belfry;The part of a tower or steeple in which bells are hung.",
	"romp;To play or frolic boisterously.",
	"dupe;One who has been deceived or who is easily deceived.",
	"despot;A ruler with absolute power.",
	"undulation;A regular rising and falling or movement to alternating sides.",
	"cronyism;Favoritism shown to old friends without regard for their qualifications, as in political appointments to office.",
	"ninny;A simpleton, a fool.",
	"condole;To express sympathy or sorrow.",
	"macropterous;Having long or large wings.",
	"gangling;Awkwardly tall or long-limbed.",
	"pliant;Easily influenced.",
	"tout;To promote or praise energetically.",
	"pallid;Lacking intensity of color or luminousness.",
	"deign;To do something that one considers beneath one's dignity.",
	"quandary;A state of uncertainty or perplexity.",
	"berth;Sufficient space for a vessel to maneuver.",
	"balkanize;To divide a territory into small, hostile states.",
	"pejorative;Implying or imputing evil.",
	"hoi polloi;The common people, the masses.",
	"bonhomie;A pleasant and affable disposition.",
	"autodidact;A self-taught person, an automath.",
	"corporeal;Of a material nature, tangible.",
	"avant garde; an intelligentsia that develops new or experimental concepts especially in the arts.",
	"tendentious;Marked by or favoring a particular point of view.",
	"gravitas;Seriousness in bearing or manner.",
	"salient;Strikingly conspicuous, prominent.",
	"albatross;A source of worry or distress.",
	"concurrent;Happening, existing, or done at the same time as something else.",
	"coy;Affectedly and often flirtatiously shy or modest.",
	"vita;A short account of a person's life, a curriculum vitae.",
	"eschatology;A belief or a doctrine concerning the ultimate or final things, such as death, the destiny of humanity, the Second Coming, or the Last Judgment.",
	"doyen;A man who is the eldest or senior member of a group.",
	"numismatic;Of or relating to coins or currency.",
	"hermaphrodite;An organism that has both kinds of reproductive organs and can produce both gametes associated with male and female sexes.",
	"adrogny;The possession of both masculine and feminine characteristics in humans.",
	"extemporaneous;Carried out or performed with little or no preparation, impromptu.",
	"ad-lib;To engage in improvisation, as during delivery of a speech.",
	"prima facie;At first sight.",
	"preclude;To make impossible, as by action taken in advance.",
	"propriety;Socially correct usages or behaviors.",
	"physiognomy;The art of judging human character from facial features.",
	"deference;A yielding of judgment or preference from respect to the wishes or opinion of another.",
	"wherewithal;The ability and means required to accomplish some task.",
	"impetuous;Acting or done quickly with little or inadequate thought.",
	"shrewd;Having or showing a clever awareness or resourcefulness, especially in practical matters, sharp.",
	"repatriate;To restore or return to the country of birth, citizenship, or origin.",
	"abscond;To hide, withdraw, or be concealed.",
	"cogent;Appealing to the intellect or powers of reasoning.",
	"hegemony;The predominance of one state or social group over others.",
	"chicanery;Deception by trickery.",
	"sophistry;A plausible but misleading or fallacious argument.",
	"mellifluous;Having a smooth rich flow.",
	"penance;An act of self-mortification or devotion performed voluntarily to show sorrow for a sin or other wrongdoing, repentance.",
	"penchant;Strong inclination.",
	"quid pro quo;Something that is given in return for something else or accepted as a reciprocal part of an exchange.",
	"vainglorious;Excessively proud of oneself.",
	"sacrilege;The violation, desecration, or profanation of sacred things.",
	"upshot;The central idea or point.",
	"clemency;A merciful, kind, or lenient act.",
	"modus operandi;A method of operation or pattern of criminal behavior so distinctive that separate crimes or wrongful conduct are recognized as the work of the same person.",
	"vitriol;Bitterly abusive feeling or expression.",
	"unbidden;Not invited, asked, or requested.",
	"kaibosh;Something that serves as a check or stop.",
	"penal;Of, relating to, or prescribing punishment, as for breaking the law.",
	"whet;To make more keen, to sharpen.",
	"caustic;Sarcastic or cutting.",
	"sangfroid;Coolness of mind, calmness, composure.",
	"dinky;Of small size or consequence.",
	"ouroboros;A serpent, dragon or worm who eats its own tail, a representation of the continuous cycle of life and death.",
	"esprit de corps;A common spirit of comradeship, enthusiasm, and devotion to a cause among the members of a group.",
	"inundate;To cover with a flood, to overflow.",
	"punctilious;Strictly attentive to minute details of form in action or conduct, precise.",
	"gastronomy;The art or science of good eating.",
	"Freudian slip;A slip of the tongue that is motivated by and reveals some unconscious aspect of the mind.",
	"fecund;Characterized by or suggestive of fertility or intellectual productivity.",
	"bap;A woman's breasts.",
	"sardonic;Marked by the use of wit that is intended to cause hurt feelings.",
	"isthmus;A narrow strip of land connecting two larger masses of land.",
	"insurgent;Rising in revolt against a government or other established authority.",
	"apropos;Fitting and to the point.",
	"transmogrify;To change thoroughly, as into a different shape or form.",
	"impinge;To encroach on or limit something, such as a right.",
	"arrears;An unpaid, overdue debt or an unfulfilled obligation.",
	"zwischenzug;A chess tactic in which a player, instead of playing the expected move, first interposes another move posing an immediate threat that the opponent must answer, and only then plays the expected move, an in-between move.",
	"distro;A contraction of the word \"distribution\" referring to something that either distributes something else, or is distributed itself.",
	"philanthropy;The effort or inclination to increase the well-being of humankind, as by charitable aid or donations.",
	"emeritus;A person retired but retaining an honorary title corresponding to that held immediately before retirement.",
	"umami;One of the five basic tastes, the savory taste of foods such as seaweed, cured fish, aged cheeses and meats.",
	"listerv;A mailing list system.",
	"rebuff;A blunt or abrupt repulse or refusal, as to an offer.",
	"maroon;To put ashore on a desolate island or coast and leave to one's fate.",
	"cauterize;To burn or sear with a cautery.",
	"amorphous;Lacking physical form or shape.",
	"pigdin;Aa simplified speech used for communication between people with different languages.",
	"cordon;A line of people, military posts, or ships stationed around an area to enclose or guard it.",
	"masticate;To chew.",
	"surfeit;To feed or supply to excess, satiety, or disgust, to overindulge.",
	"portent;An indication of something important or calamitous about to occur.",
	"municipal;Having local self-government.",
	"intelligentsia;The intellectual elite of a society.",
	"perennial;Appearing again and again or year after year, recurrent",
	"perdition;Loss of the soul, eternal damnation.",
	"curmudgeon;An ill-tempered person full of resentment and stubborn notions.",
	"copacetic;Very satisfactory or acceptable.",
	"notwithstanding;In spite of, without being opposed or prevented by.",
	"entropy;A measure of the disorder or randomness in a closed system.",
	"ontological;Of or relating to essence or the nature of being.",
	"idiosyncrasy;A structural or behavioral characteristic peculiar to an individual or group.",
	"nomophobia;Fear of being without access to a working cell phone.",
	"sychophant;a person who uses flattery to win favour from individuals wielding influence."
];

DOOSWORDBANK =
[
	"ameneurosis;The half-forlorn, half-escapist ache of a train whistle calling in the distance at night.",
	"gnasche;The intense desire to bite deeply into the forearm of someone you love.",
	"rollover reaction;When your dream about someone you know skews how you feel about them all the next day, an emotion you are unable—and unwilling—to shake.",
	"dialecstatic;Hearing a person with a thick accent pronounce a certain phrase and wanting them to repeat it over and over until the vowels pool in the air and congeal into a linguistic taffy you could break apart and give as presents.",
	"scabulous;Proud of a scar on your body, an autograph signed to you by a world grateful for your continued willingness to play with her, even when you don’t feel like it.",
	"the McFly effect;The phenomenon of observing your parents interact with people they grew up with, which reboots their personalities into youth mode.",
	"lalalalia;The realization while talking to yourself that someone else is within earshot, which leads you to crossfade into mumbled singing.",
	"dream fever;The intense heat on the skin of a sleeping person.",
	"la cuna;A twinge of sadness that there’s no frontier left.",
	"Funkenzwangsvorstellung;The instinctive trance of a campfire in the dark.",
	"moriturism;The insomnia-borne jolt of awareness that you will die.",
	"lethobenthos;The habit of forgetting how important someone is to you until you see them again in person.",
	"deep gut;An emotion you haven’t felt in years that you might have forgotten about completely if your emotional playlist hadn’t been left on shuffle.",
	"nementia;The post-distraction effort to recall the reason why you’re feeling particularly anxious or angry or excited.",
	"swish fulfillment;The feeling of delicate luck after casually tossing something across the room and hitting your target so crisply and perfectly that you feel no desire to even attempt another shot.",
	"the standard blues;The sad awareness that the unfolding plot of your life feels new and profound but is not unique.",
	"backmasking;The instinctive tendency to see someone as you knew them in their youth.",
	"oleka;The awareness of how few days are memorable.",
	"waldosia;A condition characterized by scanning faces in a crowd looking for a specific person who would have no reason to be there.",
	"hiybbprqag;The feeling that everything original has already been done.",
	"apomakrysmenophobia;Fear that your connections with people are ultimately shallow.",
	"yu yi;The desire to feel intensely again.",
	"ellipsism;Sadness that you’ll never be able to know how history will turn out.",
	"aimonomia;Fear that learning the name of something—a bird, a constellation, an attractive stranger—will somehow ruin it.",
	"hanker sore;Finding a person so attractive it actually kinda pisses you off.",
	"flashover;The moment a conversation becomes real and alive.",
	"antematter;The dream versions of things in your life.",
	"lapyear;The age at which you become older than your parents were when you were born.",
	"ambedo;A kind of melancholic trance in which you become completely absorbed in vivid sensory details—raindrops skittering down a window, tall trees leaning in the wind, clouds of cream swirling in your coffee—which leads to a dawning awareness of the haunting fragility of life.",
	"trumspringa;The temptation to step off your career track and become a shepherd in the mountains.",
	"contact high-five;An innocuous touch by someone just doing their job—a barber, yoga instructor or friendly waitress—that you enjoy more than you’d like to admit.",
	"slipcast;The default expression that your face automatically reverts to when idle—amused, melancholic, pissed off—which occurs when a strong emotion gets buried and forgotten in the psychological laundry of everyday life.",
	"degrasse;Entranced and unsettled by the vastness of the universe.",
	"Zielschmerz;The exhilarating dread of finally pursuing a lifelong dream.",
	"the wends;Frustration that you’re not enjoying an experience as much as you should.",
	"moledro;A feeling of resonant connection with an author or artist you’ll never meet.",
	"mahpiohanzia;The disappointment of being unable to fly.",
	"xeno;The smallest measurable unit of human connection.",
	"anthrodynia;A state of exhaustion with how shitty people can be to each other.",
	"heartworm;A relationship or friendship that you can’t get out of your head.",
	"chrysalism;The amniotic tranquility of being indoors during a thunderstorm.",
	"kairosclerosis;The moment you realize that you’re currently happy—consciously trying to savor the feeling—which prompts your intellect to identify it.",
	"klexos;The art of dwelling in the past.",
	"anchorage;The desire to hold on to time as it passes.",
	"ecstatic shock;The surge of energy upon catching a glance from someone you like which scrambles your ungrounded circuits and tempts you to chase that feeling with a kite and a key.",
	"jouska;A hypothetical conversation that you compulsively play out in your head—a crisp analysis, a cathartic dialogue, a devastating comeback—which serves as a kind of psychological batting cage where you can connect more deeply with people than in the small ball of everyday life.",
	"the tilt shift;A phenomenon in which your lived experience seems oddly inconsequential once you put it down on paper.",
	"Mauerbauertraurigkeit;The inexplicable urge to push people away.",
	"kenopsia;The eerie, forlorn atmosphere of a place that’s usually bustling with people but is now abandoned and quiet.",
	"sonder;The realization that each random passerby is living a life as vivid and complex as your own—populated with their own ambitions, friends, routines, worries and inherited craziness—an epic story that continues invisibly around you like an anthill sprawling deep underground.",
	"rubatosis;The unsettling awareness of your own heartbeat.",
	"fata organa;A flash of real emotion glimpsed in someone sitting across the room.",
	"la gaudiere;The glint of goodness inside people.",
	"daguerreologue;An imaginary interview with an old photo of yourself.",
	"reverse shibboleth;The practice of answering a cellphone with a generic \"Hello?\" as if you didn’t already know exactly who was calling.",
	"mal de coucou;A phenomenon in which you have an active social life but very few close friends which is a form of acute social malnutrition in which even if you devour an entire buffet of chitchat, you’ll still feel pangs of hunger.",
	"fitzcarraldo;An image that somehow becomes lodged deep in your brain which then grows into a wild and impractical vision that keeps scrambling back and forth in your head like a dog stuck in a car that’s about to arrive home, just itching for a chance to leap headlong into reality.",
	"enouement;The bittersweetness of having arrived here in the future, where you can finally get the answers to how things turn out in the real world.",
	"semaphorism;A conversational hint that you have something personal to say on the subject but don’t go any further.",
	"monachopsis;The subtle but persistent feeling of being out of place.",
	"mimeomia;The frustration of knowing how easily you fit into a stereotype.",
	"kuebiko;A state of exhaustion inspired by acts of senseless violence.",
	"opia;The ambiguous intensity of looking someone in the eye.",
	"anemoia;Nostalgia for a time you've never known",
	"adomania;The sense that the future is arriving ahead of schedule.",
	"catoptric tristesse;The sadness that you’ll never really know what other people think of you, whether good, bad or if at all.",
	"Nodus Tollens;The realization that the plot of your life doesn’t make sense to you anymore.",
	"anecdoche;A conversation in which everyone is talking but nobody is listening.",
	"gnossienne;A moment of awareness that someone you’ve known for years still has a private and mysterious inner life.",
	"keyframe;A moment that seemed innocuous at the time but ended up marking a diversion into a strange new era of your life which prevents you from rewinding the past, but allows you to move forward without endless buffering.",
	"silience;The kind of unnoticed excellence that carries on around you every day.",
	"rigor samsa;A kind of psychological exoskeleton that can protect you from pain and contain your anxieties.",
	"adronitis;Frustration with how long it takes to get to know someone.",
	"midsummer;A feast celebrated on the day of your 26th birthday, which marks the point at which your youth finally expires as a valid excuse.",
	"paro;The feeling that no matter what you do is always somehow wrong.",
	"dead reckoning;To find yourself bothered by someone’s death more than you would have expected.",
	"nighthawk;A recurring thought that only seems to strike you late at night.",
	"Ruckkehrunruhe;The feeling of returning home after an immersive trip only to find it fading rapidly from your awareness.",
	"vellichor;The strange wistfulness of used bookstores, which are somehow infused with the passage of time.",
	"vemodalen;The frustration of photographing something amazing when thousands of identical photos already exist.",
	"lachesism;Longing for the clarity of disaster.",
	"liberosis;The desire to care less about things.",
	"keta;An image that inexplicably leaps back into your mind from the distant past.",
	"occhiolism;The awareness of the smallness of your perspective.",
	"the meantime;The moment of realization that your quintessential future self isn’t ever going to show up.",
	"kudoclasm;When lifelong dreams are brought down to Earth.",
	"avenoir;The desire that memory could flow backward.",
	"onism;The frustration of being stuck in just one body, that inhabits only one place at a time.",
	"exulansis;The tendency to give up trying to talk about an experience because people are unable to relate to it.",
	"lutalica;The part of your identity that doesn't fit into categories.",
	"moment of tangency;A glimpse of what might have been.",
	"wytai;A feature of modern society that suddenly atrikes you as absurd and grotesque.",
	"Zenosyne;The sense that time keeps going faster.",
	"Altschmerz;Weariness with the same old issues that you’ve always had.",
	"midding;Feeling the tranquil pleasure of being near a gathering but not quite in it.",
	"lilo;A friendship that can lie dormant for years only to pick right back up instantly.",
	"agnosthesia;The state of not knowing how you really feel about something.",
	"aftersome;Astonished to think back on the bizarre sequence of accidents that brought you to where you are today.",
	"ringlorn;The wish that the modern world felt as epic as the one depicted in old stories and folktales.",
	"austice;A wistful omen of the first sign of autumn",
	"amicy;The mystery of what goes on behind the scenes of your social life.",
	"aulasy;The sadness that there's no way to convey a powerful memory to people who weren't there at the time.",
	"etterath;The feeling of emptiness after a long and arduous process is finally complete.",
	"watashiato;Curiosity about the impact you've had on thelives of the people you know."
];

/**
 * Returns the string at index item when a string delimited by semi-colons
 * is split into an array.
 *
 * To be used with the WORDBANK array to get attributes of words.
 *
 * @param  string the string that is delimited by semi-colons that will be
 *                broken up into an array
 * @param  item   the number that describes the index of the array that will
                  be returned
 * @return        the string at index item
 */
function getWordDetail(string, item)
{
	// INSTEAD OF "string", MAKE IT INDEX?
	var detail = string.split(";")[item];

	return detail;
}

// Finds the index of an item in an array
// Iterates through the array and looks for an index that matches the item, and reports the number of the item.
function findArrayIndex(testArray, item)
{
	for (var i = 0; i < testArray.length; i++)
	{
		console.log(testArray[i] + " i: " + i);
		if (testArray[i] == item)
		{
			return i;
		}
	}
}
